import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/section/navbar";
import { Footer } from "@/components/section/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar
                logoText="Iconic Builders & Developers"
                navItems={[
                  { label: "Home", href: "#" },
                  { label: "About", href: "#" },
                  { label: "Pages", href: "#" },
                  { label: "Cart (0)", href: "#" },
                ]}
                ctaText="Start exploring"
              />
        <main>
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
